import { StyleSheet } from "react-native";
import { colors } from "../components/theme";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: 16, paddingBottom: 32 },
  greeting: { color: colors.textPrimary, fontSize: 28, fontWeight: "700" },
  subtitle: { color: colors.textSecondary, marginTop: 6, marginBottom: 14 },
  title: { color: colors.textPrimary, fontSize: 24, fontWeight: "700" },
  card: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  sectionTitle: { color: colors.textPrimary, fontSize: 17, fontWeight: "600" },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" },
  statCard: { width: "48%" },
  statLabel: { color: colors.textSecondary, fontSize: 13 },
  statValue: { color: colors.textPrimary, marginTop: 10, fontSize: 22, fontWeight: "700" },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  rowGap: { flexDirection: "row", alignItems: "center", gap: 10 },
  iconBtn: {
    backgroundColor: colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#26303A",
    padding: 9,
  },
  filterRow: { flexDirection: "row", gap: 8, marginTop: 14, marginBottom: 12, flexWrap: "wrap" },
  filterTab: {
    borderRadius: 999,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: "#27303A",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  filterTabActive: { borderColor: colors.primary, backgroundColor: "#1A2633" },
  filterText: { color: colors.textSecondary, fontSize: 13 },
  filterTextActive: { color: colors.primary, fontWeight: "600" },
  contestMeta: { marginTop: 8, marginBottom: 12, flexDirection: "row", alignItems: "center", gap: 6 },
  dot: { color: colors.textSecondary },
  primaryBtn: {
    marginTop: 8,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignSelf: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  primaryBtnText: { color: "#0D1117", fontWeight: "700" },
  listItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#222B36",
  },
  itemTitle: { color: colors.textPrimary, fontSize: 16, fontWeight: "600" },
  itemSubtitle: { color: colors.textSecondary, marginTop: 4 },
  muted: { color: colors.textSecondary, fontSize: 12 },
  heatmapGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 6 },
  heatCell: { width: 18, height: 18, borderRadius: 4 },
  statusPill: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  statusSolved: { backgroundColor: "rgba(63,185,80,0.15)" },
  statusPending: { backgroundColor: "rgba(210,153,34,0.15)" },
  statusText: { color: colors.textPrimary, fontSize: 12, fontWeight: "600" },
  actionRow: { marginTop: 10, flexDirection: "row", gap: 8, flexWrap: "wrap" },
  secondaryBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2A3440",
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  secondaryBtnText: { color: colors.textPrimary, fontSize: 12 },
  searchWrap: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#26303A",
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchInput: { flex: 1, color: colors.textPrimary, paddingVertical: 10 },
  titleInput: {
    borderWidth: 1,
    borderColor: "#293340",
    borderRadius: 10,
    color: colors.textPrimary,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
  },
  contentInput: {
    minHeight: 100,
    borderWidth: 1,
    borderColor: "#293340",
    borderRadius: 10,
    color: colors.textPrimary,
    paddingHorizontal: 10,
    paddingVertical: 10,
    textAlignVertical: "top",
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#202A35",
    justifyContent: "center",
    alignItems: "center",
  },
});
